
/* Drop Tables */

DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE PROVIDERS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE CUSTOMERS
(
	-- 고객ID
	ID varchar2(30) NOT NULL,
	-- 암호
	PASSWORD varchar2(30) NOT NULL,
	-- 고객명
	CUST_NAME varchar2(30) NOT NULL,
	-- 생년월일
	BIRTH_DATE date,
	-- 이메일
	EMAIL varchar2(50) NOT NULL,
	-- 집 전화번호
	HOME_PHONE varchar2(30),
	-- 휴대폰 번호
	MOBILE_PHONE varchar2(30),
	-- 우편번호
	POST_CODE varchar2(20),
	-- 주소
	ADDRESS varchar2(100),
	-- 포인트
	POINT number(10) DEFAULT 0,
	PRIMARY KEY (ID)
);


CREATE TABLE PRODUCTS
(
	-- 상품 코드
	PROD_CODE varchar2(20) NOT NULL,
	-- 상품명
	PROD_NAME varchar2(100) NOT NULL,
	-- 사이즈
	PROD_SIZE varchar2(50),
	-- 사진
	PROD_PIC varchar2(100),
	-- 상세설명
	PROD_DETAIL varchar2(4000),
	-- 단가
	PROD_COST number(10) DEFAULT 0,
	-- 재고
	PROD_STOCK number(5) DEFAULT 0,
	-- 최소유지재고
	PROD_STOCK_MIN number(5) DEFAULT 0,
	-- 사업자등록번호
	PRO_NO varchar2(30) NOT NULL,
	PRIMARY KEY (PROD_CODE)
);


CREATE TABLE PROVIDERS
(
	-- 사업자등록번호
	PRO_NO varchar2(30) NOT NULL,
	-- 사업자명
	PRO_NAME varchar2(30) NOT NULL,
	-- 대표이사 이름
	PRO_CEO varchar2(30),
	-- 대표 전화번호
	PRO_PHONE varchar2(30),
	-- 대표 팩스번호
	PRO_FAX varchar2(30),
	-- 우편번호
	PRO_POST varchar2(20),
	-- 주소
	PRO_ADDRESS varchar2(100),
	-- 이메일
	PRO_EMAIL varchar2(50),
	-- 상품 코드
	PROD_CODE varchar2(20) NOT NULL,
	PRIMARY KEY (PRO_NO)
);



/* Create Foreign Keys */

ALTER TABLE PROVIDERS
	ADD FOREIGN KEY (PROD_CODE)
	REFERENCES PRODUCTS (PROD_CODE)
;



/* Comments */

COMMENT ON COLUMN CUSTOMERS.ID IS '고객ID';
COMMENT ON COLUMN CUSTOMERS.PASSWORD IS '암호';
COMMENT ON COLUMN CUSTOMERS.CUST_NAME IS '고객명';
COMMENT ON COLUMN CUSTOMERS.BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN CUSTOMERS.EMAIL IS '이메일';
COMMENT ON COLUMN CUSTOMERS.HOME_PHONE IS '집 전화번호';
COMMENT ON COLUMN CUSTOMERS.MOBILE_PHONE IS '휴대폰 번호';
COMMENT ON COLUMN CUSTOMERS.POST_CODE IS '우편번호';
COMMENT ON COLUMN CUSTOMERS.ADDRESS IS '주소';
COMMENT ON COLUMN CUSTOMERS.POINT IS '포인트';
COMMENT ON COLUMN PRODUCTS.PROD_CODE IS '상품 코드';
COMMENT ON COLUMN PRODUCTS.PROD_NAME IS '상품명';
COMMENT ON COLUMN PRODUCTS.PROD_SIZE IS '사이즈';
COMMENT ON COLUMN PRODUCTS.PROD_PIC IS '사진';
COMMENT ON COLUMN PRODUCTS.PROD_DETAIL IS '상세설명';
COMMENT ON COLUMN PRODUCTS.PROD_COST IS '단가';
COMMENT ON COLUMN PRODUCTS.PROD_STOCK IS '재고';
COMMENT ON COLUMN PRODUCTS.PROD_STOCK_MIN IS '최소유지재고';
COMMENT ON COLUMN PRODUCTS.PRO_NO IS '사업자등록번호';
COMMENT ON COLUMN PROVIDERS.PRO_NO IS '사업자등록번호';
COMMENT ON COLUMN PROVIDERS.PRO_NAME IS '사업자명';
COMMENT ON COLUMN PROVIDERS.PRO_CEO IS '대표이사 이름';
COMMENT ON COLUMN PROVIDERS.PRO_PHONE IS '대표 전화번호';
COMMENT ON COLUMN PROVIDERS.PRO_FAX IS '대표 팩스번호';
COMMENT ON COLUMN PROVIDERS.PRO_POST IS '우편번호';
COMMENT ON COLUMN PROVIDERS.PRO_ADDRESS IS '주소';
COMMENT ON COLUMN PROVIDERS.PRO_EMAIL IS '이메일';
COMMENT ON COLUMN PROVIDERS.PROD_CODE IS '상품 코드';



